In [ ]:
import glob
import numpy as np
import pickle
import pandas as pd
from keras.applications.inception_v3 import InceptionV3
from keras.preprocessing import image


In [ ]:
DATASET_PATH = "drive/MyDrive/flickr8/captions.txt"
IMAGES_PATH = "drive/MyDrive/flickr8/Images/"

In [ ]:
model = InceptionV3(weights='imagenet')

96124928/96112376 [==============================] - 1s 0us/step


In [ ]:
from keras.models import Model

new_input = model.input
hidden_layer = model.layers[-2].output

feature_extractor = Model(new_input, hidden_layer)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv(DATASET_PATH)

In [ ]:
def preprocess_input(x):
    x /= 255.
    x -= 0.5
    x *= 2.
    return x

In [ ]:
def preprocess(image_path):
    img = image.load_img(image_path, target_size=(299, 299))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)

    x = preprocess_input(x)
    return x

In [ ]:
def encode(image):
    image = preprocess(IMAGES_PATH + image)
    temp_enc = feature_extractor.predict(image)
    temp_enc = np.reshape(temp_enc, temp_enc.shape[1])
    return temp_enc

In [ ]:
encoded_dict = {}

for index, row in df.iterrows():
  try:
    print(row["image"])
    if row["image"] not in encoded_dict:
      encoded = encode(row["image"])
      encoded_dict[row["image"]] = encoded
  except Exception as e:
    print(e)
    continue

Output streaming troncato alle ultime 5000 righe.
[0.31240106 0.46344805 0.2804604  ... 0.84698474 0.02164347 0.46304867]
2635164923_2a774f7854.jpg
1177994172_10d143cb8d.jpg
1093716555_801aacef79.jpg
2776029171_5abdd5a22f.jpg
[0.9880143  0.2993184  0.9133328  ... 0.5926757  1.3111012  0.13214129]
3111482098_11c0f4f309.jpg
[0.079908   0.8794483  0.29384875 ... 0.06177258 0.28372782 0.48792386]
537479916_c033897fac.jpg
3475092236_cf45d383c7.jpg
1299459550_1fd5594fa2.jpg
[0.34059137 0.07430837 0.11296771 ... 0.62529635 0.03339087 0.22359644]
3214579977_fa9fb006a6.jpg
[0.20789042 0.12906933 0.21503158 ... 1.1671346  1.0212373  0.35683072]
3316725440_9ccd9b5417.jpg
3611672054_45edd3e08f.jpg
[0.16584289 0.05249483 0.25059724 ... 0.07391895 0.40062094 0.27407208]
3605100550_01214a1224.jpg
524036004_6747cf909b.jpg
[1.090592   0.03166898 0.47751886 ... 0.5861256  1.4526138  0.31573105]
2341254813_c53a5ef27a.jpg
3406116788_c8f62e32d1.jpg
[0.5090096  0.46028134 1.3164418  ... 0.17493805 0.7226164

In [ ]:
len(df)

8091

In [ ]:
from google.colab import files

with open("encoded_inception.p", "wb") as encoded_pickle:
    pickle.dump(encoded_dict, encoded_pickle)
    files.download("encoded_inception.p")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df1 = pd.DataFrame.from_dict(encoded_dict, orient="index")

In [ ]:
df1.to_csv("encoded.csv")

files.download("encoded.csv")  

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>